plugins { id 'com.android.application' }

android {
    namespace 'com.mkuu.ai'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mkuu.ai'
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName '1.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }
}
